# Generated by Django 5.1.7 on 2026-08-29 00:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articlepage_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('explore', 'Explore'), ('legal', 'Legal')], default='explore', max_length=20)),
                ('label_en', models.CharField(max_length=60)),
                ('label_bn', models.CharField(blank=True, max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['column', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='about, contact, privacy, …', unique=True)),
                ('title_en', models.CharField(max_length=150)),
                ('title_bn', models.CharField(blank=True, max_length=150)),
                ('body_en', wagtail.fields.RichTextField()),
                ('body_bn', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'standing page',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=60)),
                ('label_bn', models.CharField(blank=True, max_length=60)),
                ('url', models.CharField(help_text='Path such as / or /category/uk', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'navigation item',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=250)),
                ('question_bn', models.CharField(blank=True, max_length=250)),
                ('context_label', models.CharField(blank=True, help_text='Short tag such as UK VISAS', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Guardian', max_length=60)),
                ('brand_kicker', models.CharField(default='UK | BANGLA', max_length=60)),
                ('brand_name_bn', models.CharField(default='ইউকে বাংলা গার্ডিয়ান', max_length=80)),
                ('tagline_en', models.CharField(blank=True, max_length=200)),
                ('tagline_bn', models.CharField(blank=True, max_length=200)),
                ('weather_london', models.CharField(blank=True, default='☁ London 18°C', max_length=60)),
                ('weather_dhaka', models.CharField(blank=True, default='☀ Dhaka 31°C', max_length=60)),
                ('gbp_to_bdt_rate', models.DecimalField(decimal_places=2, default=152.5, max_digits=8)),
                ('fx_trend_note_en', models.CharField(blank=True, max_length=80)),
                ('fx_trend_note_bn', models.CharField(blank=True, max_length=80)),
                ('footer_blurb_en', models.TextField(blank=True)),
                ('footer_blurb_bn', models.TextField(blank=True)),
                ('footer_badge_en', models.CharField(blank=True, max_length=120)),
                ('footer_badge_bn', models.CharField(blank=True, max_length=120)),
                ('copyright_en', models.CharField(blank=True, max_length=160)),
                ('copyright_bn', models.CharField(blank=True, max_length=160)),
                ('newsletter_footnote_en', models.CharField(blank=True, max_length=160)),
                ('newsletter_footnote_bn', models.CharField(blank=True, max_length=160)),
                ('home_lead_heading_en', models.CharField(blank=True, max_length=120)),
                ('home_lead_heading_bn', models.CharField(blank=True, max_length=120)),
                ('home_across_heading_en', models.CharField(blank=True, max_length=120)),
                ('home_across_heading_bn', models.CharField(blank=True, max_length=120)),
                ('home_more_heading_en', models.CharField(blank=True, max_length=120)),
                ('home_more_heading_bn', models.CharField(blank=True, max_length=120)),
                ('home_opinion_heading_en', models.CharField(blank=True, max_length=120)),
                ('home_opinion_heading_bn', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('glyph', models.CharField(help_text='Single character shown in the icon circle', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=200)),
                ('text_bn', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'breaking-news ticker item',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TrendingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Without the # prefix', max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='image_caption_bn',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='image_caption_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='image_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL, used when no image is uploaded'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='pull_quote_bn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='pull_quote_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='role_bn',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='author',
            name='role_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label_en', models.CharField(max_length=150)),
                ('label_bn', models.CharField(blank=True, max_length=150)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('poll', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='news.poll')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
