# Generated by Django 5.1.7 on 2026-09-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_pageview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'newsletter subscriber'},
        ),
    ]
