# Generated by Django 5.1.7 on 2026-09-01 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newslettersubscription_options'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_banner',
            field=models.ForeignKey(blank=True, help_text='Recommended 970×90 or 728×90', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_banner_alt',
            field=models.CharField(blank=True, default='Advertisement', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_banner_enabled',
            field=models.BooleanField(default=False, help_text='Show the banner beside the logo in the header'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_banner_image_url',
            field=models.URLField(blank=True, help_text='External image URL, used if no image is uploaded'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_banner_link',
            field=models.URLField(blank=True, help_text='Where the banner links to when clicked'),
        ),
    ]
