# Generated by Django 5.1.7 on 2026-09-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_sitesettings_header_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastheadMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_en', models.CharField(max_length=120)),
                ('role_bn', models.CharField(blank=True, max_length=120)),
                ('name_en', models.CharField(max_length=150)),
                ('name_bn', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'masthead / editorial team member',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
