# Generated by Django 5.1.7 on 2026-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_mastheadmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, help_text='One line per line'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_emails',
            field=models.TextField(blank=True, help_text='One email address per line'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_heading_bn',
            field=models.CharField(blank=True, default='সম্পাদকীয় যোগাযোগ', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_heading_en',
            field=models.CharField(blank=True, default='Editorial Contact', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phones',
            field=models.TextField(blank=True, help_text='One phone number per line'),
        ),
    ]
