# Generated by Django 5.1.7 on 2026-09-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_sitesettings_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_london', models.CharField(blank=True, max_length=60)),
                ('weather_dhaka', models.CharField(blank=True, max_length=60)),
                ('gbp_to_bdt_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'live status strip',
                'verbose_name_plural': 'live status strip',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_status_strip',
            field=models.BooleanField(default=False, help_text="Auto-update weather + exchange rate from the internet (run 'refresh_live_status' on a schedule). When off, the values below are used as typed."),
        ),
    ]
