# Generated by Django 5.1.7 on 2026-09-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_livestatus_sitesettings_auto_status_strip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.AddField(
            model_name='section',
            name='nav_label_bn',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='section',
            name='nav_label_en',
            field=models.CharField(blank=True, help_text='Optional shorter label for the menu (defaults to the name)', max_length=60),
        ),
        migrations.AddField(
            model_name='section',
            name='show_in_nav',
            field=models.BooleanField(default=False, help_text='Show this section as a link in the header menu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_show_home',
            field=models.BooleanField(default=True, help_text="Show a 'Home' link first in the header menu"),
        ),
        migrations.AlterField(
            model_name='section',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in the header menu and footer'),
        ),
    ]
