# Generated by Django 5.1.7 on 2026-09-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_delete_menuitem_section_nav_label_bn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the URL (/category/…). Leave blank to generate it from the English name — English letters only.', unique=True),
        ),
    ]
