# Generated by Django 5.1.7 on 2026-09-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='about, contact, privacy, …', unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used in the URL (/category/…). Leave blank to generate it from the English name.', unique=True),
        ),
    ]
