# Generated by Django 5.1.7 on 2026-09-08 02:10

import news.slugs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_infopage_slug_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='slug',
            field=news.slugs.BanglaSlugField(help_text='about, contact, privacy, …', unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=news.slugs.BanglaSlugField(blank=True, help_text='Used in the URL (/category/…). Leave blank to generate it from the English name.', unique=True),
        ),
    ]
