# Generated by Django 5.1.7 on 2026-09-08 02:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_infopage_slug_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body_bn',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body_en',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='title_bn',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
